name: Publish Package to npm No OTP
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'     
        required: true        

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: step-security/harden-runner@v1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            hooks.slack.com:443
            nodejs.org:443
            prod.api.stepsecurity.io:443
            registry.npmjs.org:443
      
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      
      - uses: ljharb/actions/node/install@main
        name: 'nvm install lts/* && npm install'
        with:
          node-version: 'lts/*'
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
      
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> .npmrc
      - run: npm publish --dry-run
      
      - run: npm publish --access public      
